name: Build Jar 
on:
  workflow_dispatch:  
    inputs:  
      logLevel:  
        description: 'Log level'  
        required: true  
        default: 'warning'
  push:  
    branches: [ "aipigpig-patch-1" ]  
  pull_request:  
    branches: [ "aipigpig-patch-1" ] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    permissions: write-all 
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up JDK 21 
        uses: actions/setup-java@v3  
        with:  
          java-version: '17'  
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.2  # 更新到支持 JDK 21 的版本
          cache-read-only: false
      - name: Grant execute permission to gradlew 
        run: chmod +x ./gradlew 
      - name: Build Jar 
        run: | 
          ./gradlew build 
          mkdir -p ${{ github.workspace }}/artifacts 
          mv target/*.jar ${{ github.workspace }}/artifacts/ 
      - name: Set Version as Environment Variable
        run: |
          RELEASE_VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}' | tr -d '\r')
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Use Version Number 
        run: | 
          echo "Version number is ${{ env.RELEASE_VERSION }}" 
      - uses: "marvinpinto/action-automatic-releases@latest"  
        with:  
          repo_token: "${{ secrets.GITHUB_TOKEN }}"  
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"  
          prerelease: false  
          title: "Release ${{ env.RELEASE_VERSION }}"  
          files: |  
            ${{ github.workspace }}/artifacts/*.jar 
      - name: DONE!!! 
        run: echo "done"
